<?php
$aMenuLinks = [
    [
        "Основные сведения",
        "/local/templates/edu_template/main/main_information/",
        [],
        [],
        ""
    ],
    [
        "Факультеты",
        "/local/templates/edu_template/main/about/faculties/",
        [],
        [],
        ""
    ],
    [
        "Филиалы",
        "/local/templates/edu_template/main/about/branches/",
        [],
        [],
        ""
    ],
    [
        "Ученый совет",
        "/local/templates/edu_template/main/about/council/",
        [],
        [],
        ""
    ],
    [
        "Структура",
        "/local/templates/edu_template/main/about/structure/",
        [],
        [],
        ""
    ],
    [
        "Руководство",
        "/local/templates/edu_template/main/about/leadership/",
        [],
        [],
        ""
    ],
    [
        "Преподаватели и сотрудники",
        "/local/templates/edu_template/main/about/staff/",
        [],
        [],
        ""
    ],
    [
        "История",
        "/local/templates/edu_template/main/about/history/",
        [],
        [],
        ""
    ],
    [
        "Устав",
        "/local/templates/edu_template/main/about/constitution/",
        [],
        [],
        ""
    ],
    [
        "Библиотека",
        "/local/templates/edu_template/main/about/library/",
        [],
        [],
        ""
    ],
    [
        "Новости",
        "/local/templates/edu_template/main/about/news/",
        [],
        [],
        ""
    ],
    [
        "Объявления",
        "/local/templates/edu_template/main/about/advertisement/",
        [],
        [],
        ""
    ],
    [
        "Лицензии",
        "/local/templates/edu_template/main/about/licenses/",
        [],
        [],
        ""
    ]
];
?>