<?php
$aMenuLinks = [
    [
        "Новости",
        "/local/templates/edu_template/main/about/news/",
        [],
        [],
        ""
    ],
    [
        "Основные сведения",
        "/local/templates/edu_template/main/main_information/",
        [],
        [],
        ""
    ],
    [
        "Факультеты",
        "/local/templates/edu_template/main/about/faculties/",
        [],
        [],
        ""
    ],
    [
        "Филиалы",
        "/local/templates/edu_template/main/about/branches/",
        [],
        [],
        ""
    ],
    [
        "Филиалы",
        "/local/templates/edu_template/main/about/council/",
        [],
        [],
        ""
    ]
];
?>